"""Scaffold, install, and manage the jmunch gateway from the CLI.

  jmunch-mcp gateway setup    → interactive first-time setup wizard
  jmunch-mcp gateway init     → write a starter ~/.jmunch/gateway.toml
  jmunch-mcp gateway install  → run the gateway as a user-level service —
                                a launchd agent on macOS, a systemd user
                                unit on Linux — plus start / stop / restart
                                / status / uninstall.

API keys live in ~/.jmunch/env (KEY=VALUE per line, mode 0600). `install`
reads that file and embeds the values into the service environment, so
the running gateway can see them.

Agent-agnostic: it scaffolds and manages the gateway HTTP service only.
Nothing here knows about any particular AI application or agent framework.
"""
from __future__ import annotations

import argparse
import os
import plistlib
import subprocess
import sys
import time
from pathlib import Path

DEFAULT_LABEL = "sh.jmunch.gateway"
_WIZARD_VERBS = ("setup", "add-upstream", "remove-upstream")
_SERVICE_VERBS = ("init", "install", "start", "stop", "restart", "status", "uninstall")
GATEWAY_VERBS = _WIZARD_VERBS + _SERVICE_VERBS

# Starter gateway config written by `jmunch-mcp gateway init`. Valid as-is;
# the user edits the [[upstream]] block to point at their provider.
_GATEWAY_TOML_TEMPLATE = """\
# jmunch gateway configuration — generated by `jmunch-mcp gateway init`.
#
# Edit the [[upstream]] block to point at your LLM provider, then either:
#   jmunch-mcp gateway install                 # run as a background service
#   jmunch-mcp gateway --config <this file>    # run in the foreground

[gateway]
listen = "127.0.0.1:7879"
default_upstream = "openai"
log_level = "INFO"

[[upstream]]
name = "openai"
kind = "openai"                      # "openai" or "anthropic"
base_url = "https://api.openai.com"
# The API key is read from $OPENAI_API_KEY by default; override with:
# api_key_env = "MY_OPENAI_KEY"

[interception]
# Tool-result payloads larger than this (bytes/4 heuristic) are handle-ified.
threshold_tokens = 2000
# auto | always | never — when to inject the jmunch drill-in verbs.
inject_tools = "auto"

[handles]
ttl_seconds = 3600
store_path = "~/.jmunch/handles.db"
max_bytes = 2000000000
"""


def _jmunch_home() -> Path:
    return Path.home() / ".jmunch"


def _default_config() -> Path:
    return _jmunch_home() / "gateway.toml"


def _default_env_path() -> Path:
    return _jmunch_home() / "env"


def _read_env_file(path: Path) -> dict[str, str]:
    """Parse a KEY=VALUE secrets file. Comments (#) and blank lines ignored.
    Values are taken verbatim (no quote stripping). Missing file → {}."""
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        s = raw.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, _, v = s.partition("=")
        k = k.strip()
        if k:
            out[k] = v.strip()
    return out


def _write_env_file(path: Path, env: dict[str, str]) -> None:
    """Write the env dict to `path` (mode 0600), preserving order."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# jmunch gateway environment — read by `jmunch-mcp gateway install`.",
        "# KEY=VALUE per line. Comments (#) and blank lines are ignored.",
        "",
    ]
    for k, v in env.items():
        lines.append(f"{k}={v}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)
    except OSError:  # pragma: no cover — non-POSIX
        pass


def _log_paths() -> tuple[Path, Path]:
    logs = _jmunch_home() / "logs"
    return logs / "gateway.out.log", logs / "gateway.err.log"


def _program_args(config: Path) -> list[str]:
    """Argv that runs the gateway with the interpreter that owns this install."""
    return [sys.executable, "-m", "jmunch_mcp", "gateway", "--config", str(config)]


def _backend() -> str | None:
    if sys.platform == "darwin":
        return "launchd"
    if sys.platform.startswith("linux"):
        return "systemd"
    return None


# --------------------------------------------------------------------------
# unit-file rendering (pure — unit-tested without touching launchctl/systemctl)
# --------------------------------------------------------------------------

def render_launchd_plist(
    label: str, config: Path, out_log: Path, err_log: Path,
    *, env: dict[str, str] | None = None,
) -> bytes:
    d: dict = {
        "Label": label,
        "ProgramArguments": _program_args(config),
        "RunAtLoad": True,
        "KeepAlive": True,
        "StandardOutPath": str(out_log),
        "StandardErrorPath": str(err_log),
        "WorkingDirectory": str(Path.home()),
    }
    if env:
        d["EnvironmentVariables"] = dict(env)
    return plistlib.dumps(d)


def _sd_quote(arg: str) -> str:
    return f'"{arg}"' if any(c.isspace() for c in arg) else arg


def render_systemd_unit(
    config: Path, out_log: Path, err_log: Path,
    *, env: dict[str, str] | None = None,
) -> str:
    exec_start = " ".join(_sd_quote(a) for a in _program_args(config))
    env_block = "".join(f"Environment={k}={v}\n" for k, v in (env or {}).items())
    return (
        "[Unit]\n"
        "Description=jmunch gateway — token-saving OpenAI/Anthropic proxy\n"
        "After=network.target\n"
        "\n"
        "[Service]\n"
        f"{env_block}"
        f"ExecStart={exec_start}\n"
        "Restart=on-failure\n"
        "RestartSec=2\n"
        f"StandardOutput=append:{out_log}\n"
        f"StandardError=append:{err_log}\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def _launchd_plist_path(label: str) -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"


def _systemd_unit_path(label: str) -> Path:
    return Path.home() / ".config" / "systemd" / "user" / f"{label}.service"


# --------------------------------------------------------------------------
# launchctl / systemctl wrappers
# --------------------------------------------------------------------------

def _run(cmd: list[str]) -> subprocess.CompletedProcess:
    try:
        return subprocess.run(cmd, capture_output=True, text=True)
    except FileNotFoundError:
        return subprocess.CompletedProcess(cmd, 127, "", f"{cmd[0]}: not found")


def _launchctl(*args: str) -> subprocess.CompletedProcess:
    return _run(["launchctl", *args])


def _systemctl(*args: str) -> subprocess.CompletedProcess:
    return _run(["systemctl", "--user", *args])


# --------------------------------------------------------------------------
# verbs
# --------------------------------------------------------------------------

def _init(config: Path, *, force: bool) -> int:
    if config.exists() and not force:
        print(f"gateway config already exists: {config}")
        print("  edit it, or pass --force to overwrite with a fresh template.")
        return 0
    config.parent.mkdir(parents=True, exist_ok=True)
    config.write_text(_GATEWAY_TOML_TEMPLATE, encoding="utf-8")
    print(f"wrote starter gateway config: {config}")
    print("  edit the [[upstream]] block, then: jmunch-mcp gateway install")
    return 0


def _install(
    label: str, config: Path, backend: str,
    *, debug_dump: bool, env_file: Path | None = None,
) -> int:
    env_extras = _read_env_file(env_file) if env_file else {}
    env = {"JMUNCH_DEBUG_DUMP": "1" if debug_dump else "0", **env_extras}

    out_log, err_log = _log_paths()
    out_log.parent.mkdir(parents=True, exist_ok=True)

    if backend == "launchd":
        plist = _launchd_plist_path(label)
        plist.parent.mkdir(parents=True, exist_ok=True)
        uid = os.getuid()
        target = f"gui/{uid}/{label}"
        # Unload any existing registration BEFORE rewriting the plist so
        # launchd doesn't keep a stale handle to the previous file content.
        _launchctl("bootout", target)
        time.sleep(0.5)  # bootout is mildly async; give launchd a tick
        plist.write_bytes(
            render_launchd_plist(label, config, out_log, err_log, env=env)
        )
        r = _launchctl("bootstrap", f"gui/{uid}", str(plist))
        # EIO ("Bootstrap failed: 5: Input/output error") almost always
        # means a leftover registration — one more bootout+bootstrap clears it.
        if r.returncode != 0 and "5: Input/output error" in r.stderr:
            _launchctl("bootout", target)
            time.sleep(0.5)
            r = _launchctl("bootstrap", f"gui/{uid}", str(plist))
        if r.returncode != 0:
            print(f"error: launchctl bootstrap failed: {r.stderr.strip()}",
                  file=sys.stderr)
            print(
                f"  manual recovery:  launchctl bootout {target} "
                f"&& pkill -f 'jmunch_mcp.*gateway' ; jmunch-mcp gateway install",
                file=sys.stderr,
            )
            return 1
        print(f"installed launchd agent: {plist}")
    else:
        unit = _systemd_unit_path(label)
        unit.parent.mkdir(parents=True, exist_ok=True)
        unit.write_text(
            render_systemd_unit(config, out_log, err_log, env=env), encoding="utf-8",
        )
        _systemctl("daemon-reload")
        r = _systemctl("enable", "--now", unit.name)
        if r.returncode != 0:
            print(f"error: systemctl enable failed: {r.stderr.strip()}", file=sys.stderr)
            return 1
        print(f"installed systemd user unit: {unit}")

    print(f"  config:     {config}")
    print(f"  logs:       {out_log}")
    print(f"  debug dump: {'on' if debug_dump else 'off'} (JMUNCH_DEBUG_DUMP)")
    if env_extras:
        print(f"  env vars:   {', '.join(env_extras)}  (from {env_file})")
    return 0


def _control(verb: str, label: str, backend: str) -> int:
    if backend == "launchd":
        return _launchd_control(verb, label)
    return _systemd_control(verb, label)


def _launchd_control(verb: str, label: str) -> int:
    plist = _launchd_plist_path(label)
    uid = os.getuid()
    target = f"gui/{uid}/{label}"

    if verb == "status":
        r = _launchctl("list", label)
        if r.returncode != 0:
            print(f"{label}: not loaded")
            return 0
        pid = next(
            (ln.split("=")[1].strip().rstrip(";")
             for ln in r.stdout.splitlines() if ln.strip().startswith('"PID"')),
            None,
        )
        print(f"{label}: running (pid {pid})" if pid else f"{label}: loaded, not running")
        return 0

    if not plist.is_file():
        print(f"error: {label} is not installed (run `jmunch-mcp gateway install`)",
              file=sys.stderr)
        return 1

    if verb == "start":
        r = _launchctl("bootstrap", f"gui/{uid}", str(plist))
    elif verb == "stop":
        r = _launchctl("bootout", target)
    elif verb == "restart":
        r = _launchctl("kickstart", "-k", target)
    elif verb == "uninstall":
        _launchctl("bootout", target)  # ignore: may already be stopped
        plist.unlink(missing_ok=True)
        print(f"removed {plist}")
        return 0
    else:  # pragma: no cover - guarded by caller
        print(f"error: unknown verb {verb}", file=sys.stderr)
        return 2

    if r.returncode != 0:
        print(f"error: launchctl {verb} failed: {r.stderr.strip()}", file=sys.stderr)
        return 1
    print(f"{label}: {verb} ok")
    return 0


def _systemd_control(verb: str, label: str) -> int:
    unit = _systemd_unit_path(label)
    name = unit.name

    if verb == "status":
        if not unit.is_file():
            print(f"{name}: not installed")
            return 0
        active = _systemctl("is-active", name).stdout.strip() or "unknown"
        pid = _systemctl("show", "--property=MainPID", "--value", name).stdout.strip()
        suffix = f" (pid {pid})" if pid and pid != "0" else ""
        print(f"{name}: {active}{suffix}")
        return 0

    if not unit.is_file():
        print(f"error: {name} is not installed (run `jmunch-mcp gateway install`)",
              file=sys.stderr)
        return 1

    if verb == "uninstall":
        _systemctl("disable", "--now", name)  # ignore: may already be stopped
        unit.unlink(missing_ok=True)
        _systemctl("daemon-reload")
        print(f"removed {unit}")
        return 0

    r = _systemctl(verb, name)
    if r.returncode != 0:
        print(f"error: systemctl {verb} failed: {r.stderr.strip()}", file=sys.stderr)
        return 1
    print(f"{name}: {verb} ok")
    return 0


def main(verb: str, argv: list[str]) -> int:
    # Interactive verbs live in cli/wizard.py.
    if verb in _WIZARD_VERBS:
        from .wizard import main as wizard_main
        return wizard_main(verb, argv)

    parser = argparse.ArgumentParser(prog=f"jmunch-mcp gateway {verb}")

    # `init` only writes a file — no platform backend needed.
    if verb == "init":
        parser.add_argument("--config", default=str(_default_config()),
                            help="where to write the config (default: %(default)s)")
        parser.add_argument("--force", action="store_true",
                            help="overwrite an existing config")
        args = parser.parse_args(argv)
        return _init(Path(args.config).expanduser(), force=args.force)

    parser.add_argument("--label", default=DEFAULT_LABEL,
                        help="service label (default: %(default)s)")
    if verb == "install":
        parser.add_argument("--config", default=str(_default_config()),
                            help="path to gateway.toml (default: %(default)s)")
        parser.add_argument(
            "--env-file", default=str(_default_env_path()),
            help="KEY=VALUE secrets file embedded into the service env "
                 "(default: %(default)s; missing file is OK)",
        )
        parser.add_argument(
            "--debug-dump", action="store_true",
            help="set JMUNCH_DEBUG_DUMP=1 in the service environment (default: 0)",
        )
    args = parser.parse_args(argv)

    backend = _backend()
    if backend is None:
        print(
            f"error: gateway service management is not supported on {sys.platform} "
            "(macOS/launchd and Linux/systemd only). Run "
            "`jmunch-mcp gateway --config <toml>` in the foreground instead.",
            file=sys.stderr,
        )
        return 2

    if verb == "install":
        config = Path(args.config).expanduser().resolve()
        if not config.is_file():
            print(f"error: no gateway config at {config}", file=sys.stderr)
            print("  run `jmunch-mcp gateway setup` (interactive) or "
                  "`jmunch-mcp gateway init`.", file=sys.stderr)
            return 2
        env_file = Path(args.env_file).expanduser()
        return _install(args.label, config, backend,
                        debug_dump=args.debug_dump, env_file=env_file)

    return _control(verb, args.label, backend)
